### ISSUE TITLE
Listview android horizontal-align not working

### ISSUE THREAD

**Issue by eleddie** [NativeScript/nativescript-angular#639]
Basically what I'm doing is a chat app, so I want my messages to be on the right and my friend's messages to be on the left.

```HTML
 <ListView #lv row="0" [items]="messages" class="list-group" separatorColor="white">
        <template let-message="item">
            <StackLayout class="message" [class.my-message]="message.uname != uname" [class.friend-message]="message.uname == uname">
                <Label [text]="message.msg" textWrap="true"></Label>
            </StackLayout>
        </template>
    </ListView>
```

The classes have this:
```CSS
.my-message {
    background-color: #F5F5F5;
    horizontal-align: right;
}
.friend-message {
    background-color: #dbeef7;
    horizontal-align: left;
}
.message{
    font-size: 15;
    margin: 2 8;
    padding: 4 8;
    color: black;
    border-radius: 4;
}
```

<img width="379" alt="screen shot 2017-01-24 at 12 25 25 am" src="https://cloud.githubusercontent.com/assets/13477629/22234183/74e45cea-e1cc-11e6-92ac-ac5b3fc39ddb.png">

On iOS it works as expected, but in android the horizontal alignment is not working, not even hardcoding it like `style="horizontal-align="right"`. The view simply stays on the left, every other style is applied but the horizontal alignment.
