### ISSUE TITLE
Remove actionbar drop shadow on android

### ISSUE THREAD

**Issue by RyanSMurphy** [NativeScript/nativescript-angular#929]
How do I remove the action bar drop shadow on android devices?

I have implemented a similar thing on ios by following: https://github.com/NativeScript/NativeScript/issues/2470

Any help appreciated.

**Comment by danielgek** [comment]
@RyanSMurphy try this:
```css
ActionBar {
    border-width: 1;
    border-color: transparent;
}
```
